apiVersion: couchbase.com/v2
kind: CouchbaseCluster
metadata:
  name: cb-appdemo
spec:
  image: registry.connect.redhat.com/couchbase/server:7.2.2-1-amd64
  cluster:
    autoCompaction:
      databaseFragmentationThreshold:
        percent: 99
      viewFragmentationThreshold:
        percent: 99
      parallelCompaction: false
      timeWindow:
        start: 08:00
        end: 20:00
        abortCompactionOutsideWindow: true
  security:
    adminSecret: cb-appdemo-admin-auth
    rbac:
      managed: true
      selector:
        matchLabels:
          cluster: appdemo-cluster
  networking:
    cloudNativeGateway:
      enabled: True
      image: registry.connect.redhat.com/couchbase/cloud-native-gateway:0.1.0-1-amd64
      tls:
        serverSecretName: appdemo-route
    tls:
      rootCAs:
        - couchbase-server-ca
      secretSource:
        serverSecretName: appdemo-route
  #   exposeAdminConsole: true
  #   adminConsoleServices:
  #     - data
  #   exposedFeatures:
  #     - xdcr
  #     - client
  #   exposedFeatureServiceType: NodePort
  #   adminConsoleServiceType: NodePort
  buckets:
    managed: true
  servers:
    - size: 3
      name: some_services
      services:
        - data
        - index
        - query
        - search
      pod:
        spec:
          imagePullSecrets:
            - name: ghcr-login-secret
---
apiVersion: couchbase.com/v2
kind: CouchbaseBucket
metadata:
  name: appbucket
spec:
  compressionMode: passive
  conflictResolution: seqno
  evictionPolicy: valueOnly
  ioPriority: high
  memoryQuota: 100Mi
  replicas: 1
  enableFlush: true
---
apiVersion: couchbase.com/v2
kind: CouchbaseUser
metadata:
  name: appdemo
  labels:
    cluster: appdemo-cluster
spec:
  fullName: "Appdemo Example"
  authDomain: local
  authSecret: appdemo-secret-user
---
apiVersion: couchbase.com/v2
kind: CouchbaseGroup
metadata:
  name: appdemo-group
  labels:
    cluster: appdemo-cluster
spec:
  roles:
    - name: bucket_full_access
      bucket: appbucket
---
apiVersion: couchbase.com/v2
kind: CouchbaseRoleBinding
metadata:
  name: appdemo-role-binding
spec:
  subjects:
    - kind: CouchbaseUser
      name: appdemo
  roleRef:
    kind: CouchbaseGroup
    name: appdemo-group
