apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    config.couchbase.com/version: 2.5.0
  creationTimestamp: null
  name: couchbase-operator-admission
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  annotations:
    config.couchbase.com/version: 2.5.0
  creationTimestamp: null
  name: couchbase-operator-admission
rules:
- apiGroups:
  - couchbase.com
  resources:
  - couchbaseclusters
  - couchbasebuckets
  - couchbaseephemeralbuckets
  - couchbasememcachedbuckets
  - couchbasereplications
  - couchbaseusers
  - couchbasegroups
  - couchbaserolebindings
  - couchbasebackups
  - couchbasebackuprestores
  - couchbaseautoscalers
  - couchbasecollections
  - couchbasecollectiongroups
  - couchbasescopes
  - couchbasescopegroups
  - couchbasemigrationreplications
  verbs:
  - get
  - list
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - get
- apiGroups:
  - storage.k8s.io
  resources:
  - storageclasses
  verbs:
  - get
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  annotations:
    config.couchbase.com/version: 2.5.0
  creationTimestamp: null
  name: couchbase-operator-admission
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: couchbase-operator-admission
subjects:
- kind: ServiceAccount
  name: couchbase-operator-admission
  namespace: default
---
apiVersion: v1
data:
  tls.crt: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURoekNDQW0rZ0F3SUJBZ0lRU2plLzZWeXRnOWgvMlFXTWlRUmdjakFOQmdrcWhraUc5dzBCQVFzRkFEQXEKTVNnd0pnWURWUVFERXg5amIzVmphR0poYzJVdGIzQmxjbUYwYjNJdFlXUnRhWE56YVc5dUlFTkJNQjRYRFRJegpNRFV6TVRJeU1qQXlOMW9YRFRNek1EVXlPREl5TWpBeU4xb3dKekVsTUNNR0ExVUVBeE1jWTI5MVkyaGlZWE5sCkxXOXdaWEpoZEc5eUxXRmtiV2x6YzJsdmJqQ0NBU0l3RFFZSktvWklodmNOQVFFQkJRQURnZ0VQQURDQ0FRb0MKZ2dFQkFMc2wzQko1VnJDU1JuSndqYUlQWDI2SzJwMmMrMm5LUnozcVVTRTFpeG9saHNrSFRVMml6RmtQMmd5WApaMWRnTWtzY3AzQVRWL00xdjU2NXVrbFh5aVYyWG5iTVlDMnYyYWxBcWEwcWRJNzRrNzdLTSs0VlNBQ0ZkNFZoCldTYk5xclZKQ0dKZXFNVnNFcHVRVVVzbTlKbDNLc01kNERUU1l3UDFWVUE0eSttQ0k4ZkFYeUtnbzNVUzVHZU8KV2Y5SThGTWQ0WUg1eEdLWVF2Q1lWaGJ0Z2xXZGplTlZzb0w0bWVTQWlBRUhsenlwNDR6N3NpUlN1LzVIdmZyRQpDdFpBNXVrckhQVzIrbWxCcXhJdGZFTlloU3FlRjlYOHNOYTdxK1k0UUd5YkxPTno3UE5vOFUvOE03czVBZVBUCm5wNm5abG5hRkx1ZmdwWjhteVc1Uys3NjRuVUNBd0VBQWFPQnF6Q0JxREFPQmdOVkhROEJBZjhFQkFNQ0JhQXcKRXdZRFZSMGxCQXd3Q2dZSUt3WUJCUVVIQXdFd0RBWURWUjBUQVFIL0JBSXdBREFkQmdOVkhRNEVGZ1FVY1d2aQpOWHhDS3phZnlLMVBLeDF1K3JRNVJuY3dId1lEVlIwakJCZ3dGb0FVcUowblRQcjBHWmhGSUJ5bkFybEI0VnloCmZtWXdNd1lEVlIwUkJDd3dLb0lvWTI5MVkyaGlZWE5sTFc5d1pYSmhkRzl5TFdGa2JXbHpjMmx2Ymk1a1pXWmgKZFd4MExuTjJZekFOQmdrcWhraUc5dzBCQVFzRkFBT0NBUUVBWk55RXl4ZnVaSTVHZFNPaW1OUHVUL1VLZHMvWApRU2dyUjZweG8yQzZuWW8vM3FvQUsyMVFaNnorVUo0WUFZZ2R1TUhUbU9yV3RPbTlMUHFVN1FkVk50aHArZTd6ClVFNFFTWU1UU3g3YzdleE9qVDl2NVJFbGxVUEpBUDlUSlBNdWpaT2Q4cThXdytkaEJKNXhZbzMxazAzcmw3clEKVWIvSGw0ckFZdy9UVFplRmlOM1BaUGRHbFY0VWpLdjIrd0JZak5ZOGZ4eUl0YmplTjBpZDRGTHdISDFvT1A2LwpPYU81a0FiWUdsU3g1WWNZNktxNlNHeStGK0x3cFpOYyt5SHVDcTlXSTIwcTg4Y1VDdkJWSHdIWUhkZ2JST0NMCnVKU2ZpNHcyejh2cWpBL2xQM1VtbzU2NWlVa1JVWDJMVVg1OFpuN3ErdDBzZTlXZXFscm1BbjFzc1E9PQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
  tls.key: LS0tLS1CRUdJTiBSU0EgUFJJVkFURSBLRVktLS0tLQpNSUlFcEFJQkFBS0NBUUVBdXlYY0VubFdzSkpHY25DTm9nOWZib3Jhblp6N2FjcEhQZXBSSVRXTEdpV0d5UWROClRhTE1XUS9hREpkblYyQXlTeHluY0JOWDh6Vy9ucm02U1ZmS0pYWmVkc3hnTGEvWnFVQ3ByU3AwanZpVHZzb3oKN2hWSUFJVjNoV0ZaSnMycXRVa0lZbDZveFd3U201QlJTeWIwbVhjcXd4M2dOTkpqQS9WVlFEakw2WUlqeDhCZgpJcUNqZFJMa1o0NVovMGp3VXgzaGdmbkVZcGhDOEpoV0Z1MkNWWjJONDFXeWd2aVo1SUNJQVFlWFBLbmpqUHV5CkpGSzcva2U5K3NRSzFrRG02U3NjOWJiNmFVR3JFaTE4UTFpRktwNFgxZnl3MXJ1cjVqaEFiSnNzNDNQczgyangKVC93enV6a0I0OU9lbnFkbVdkb1V1NStDbG55YkpibEw3dnJpZFFJREFRQUJBb0lCQVFDQUd2bGJGLzRVWGZ5bApCNUNiOTRQdXlsTzlnaURER0xqTmxDQzI1OHp4Ti9EY21RZjhkYzBGeGdrUGgzQXc2bU5pOFJsWWFaVlJvV0FxCnlaM1A2SzB5R2FXdUVsWmZ6N2poMTZhT0o3cWp4MXB6Ump4bjQ5OW1vL1hkc25aeFRtVmxOTG50aERobzg0S0YKUkRPeGl0ZnlXUlZIZktMbDVZSHJ5cnJ4ZkM5eEJmeno4Q0RkRzZTTnIzUC8vWHo3ZXBSaVNtc3N3MUFpTVlnOQp1eDNPaUdYdHY4SzlkdVFyV1pNNkhLOXFtajIwbHhWRjI0NTdHZUx3YnR0THVaNjBsWnlwSkIwOEUvN0NBbkRnCktFeVRsMEJZWDJzSkJkaHBsNk5qNWpnRXp2ZVlSdDZyZ2dQa2VCUmdPY2gxWmU5dFNlNklQWUFpMlBNOFdUaDAKOHNzaGs0YmRBb0dCQU1zdHhKRGFUNDAvbHEvbVdqdDA0dmVlTHRsQkIydzJhRWNBM2FBTFRQUlJSeE5wcGFjYgo1UkY1Q1NNdXQrRVVCM0ozUnlrOFhaNEFZOGpkeHM5VmppelNScXRFbVcrTExGVnloTHZyZTc4SDZlMW1Kb29tCkVCdHoxSVlNZllGdTJTc1k5R0hPeGYxbkxHeVJxTjljOHlZYjlkbUlhY0Q2YlZFeUlDRUwwV21UQW9HQkFPdk4KTHBoTUtQak5KeVZFQ2RLZ2hPK1R1LzJSNzdzL0NiZ3VkWUxHUFkrcVVFZENFWUNrUWQ5SlFaNUtTdlpFUmJ3Rgo2Um50ZnhWV3YyNStRMC9MUHdzRDBvMVNXMzVLVXNuaERKVW9MSTBwOGxwaFo4cFQ0Y2EzNjRQWmUyNWpmOXRtCk5hMmRnVHlXTE9QQmlIak85ZzNGdVRtTWdzRDY3WTJWanlob211alhBb0dBZlA5Z1FmbDlIWm4wVzYwczhBMCsKSVRhNC9jR3JEbUQra0VneEVPaEM1TUFvS1FKQy9tY0Q2MWI2VHlITDBIWWhDc1BsRExKdHFlbjFlYnN2TjVrYwpDZWtudnZCS01UeCsvdWFnVUhoVVBqZGhMRU0vREpqVUtmOTl6U1pjQkVnczVQM0tRMjRSa285cDNqVlNubkF4CnlzMUMyQnk3YXhUbU1pRFRjV0V5Nlc4Q2dZRUFuaGgvZVJUM0UzbFpHWjg0aHNPZzNaQkxwb05HSEdEemYwMkcKOUJzK0F5akprajAxeHU1YVMvNnR4QmREazBITEQzbFhCRTg3dVc3a0FvMGRURTZWQWltWjdhNmVNVnBiajRjWQpESmxXNVg2T1F4S3pwKy85bkdLTHdXYjdYdFBQVWFhQnJ0bS9ZSU8vclNTQS81NmpVakNUTTRhRjFDVnBTRmhTCkYyR3JHeGtDZ1lCam9tWHVOK240SzNCOXRpKzFRQlZ6RXdHeWt5ZHEwT28wUXF3Z3FaQkpCQmNGbjhUaGlEa04KckgyMDc1aWRwcVo4Z3RHMURxTlB3TFB5V2Z0SDdzZFVFY216RzcrTXI5cnl4d3B6ZUo2T2hsZ1pKbWVYTGFkUQpFVEVlRFZZOExic0VTMWVqc0V5NzVsZHAvY1A2NC92ZUhXMXlRQUFiclZOREkxWHg1NlRQcGc9PQotLS0tLUVORCBSU0EgUFJJVkFURSBLRVktLS0tLQo=
kind: Secret
metadata:
  annotations:
    config.couchbase.com/version: 2.5.0
  creationTimestamp: null
  name: couchbase-operator-admission
---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    config.couchbase.com/version: 2.5.0
  creationTimestamp: null
  name: couchbase-operator-admission
spec:
  replicas: 1
  selector:
    matchLabels:
      app: couchbase-operator-admission
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: couchbase-operator-admission
    spec:
      containers:
      - args:
        - -zap-log-level=info
        - -tls-cert-file=/var/run/secrets/couchbase.com/couchbase-operator-admission/tls.crt
        - -tls-private-key-file=/var/run/secrets/couchbase.com/couchbase-operator-admission/tls.key
        - -validate-secrets=true
        - -validate-storage-classes=true
        command:
        - couchbase-admission-controller
        image: ghcr.io/cb-vanilla/admission-controller:2.6.1-106
        imagePullPolicy: IfNotPresent
        name: couchbase-operator-admission
        ports:
        - containerPort: 8443
          name: https
        readinessProbe:
          httpGet:
            path: /readyz
            port: https
            scheme: HTTPS
        resources: {}
        volumeMounts:
        - mountPath: /var/run/secrets/couchbase.com/couchbase-operator-admission
          name: couchbase-operator-admission
          readOnly: true
      securityContext:
        runAsNonRoot: true
      serviceAccountName: couchbase-operator-admission
      volumes:
      - name: couchbase-operator-admission
        secret:
          secretName: couchbase-operator-admission
      imagePullSecrets:
        - name: ghcr-login-secret
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    config.couchbase.com/version: 2.5.0
  creationTimestamp: null
  name: couchbase-operator-admission
spec:
  ports:
  - port: 443
    protocol: TCP
    targetPort: 8443
  selector:
    app: couchbase-operator-admission
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  annotations:
    config.couchbase.com/version: 2.5.0
  creationTimestamp: null
  name: couchbase-operator-admission
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURJVENDQWdtZ0F3SUJBZ0lSQUxXWm4wMmhZN2xXVGd4cGsxdlBnV0F3RFFZSktvWklodmNOQVFFTEJRQXcKS2pFb01DWUdBMVVFQXhNZlkyOTFZMmhpWVhObExXOXdaWEpoZEc5eUxXRmtiV2x6YzJsdmJpQkRRVEFlRncweQpNekExTXpFeU1qSXdNamRhRncwek16QTFNamd5TWpJd01qZGFNQ294S0RBbUJnTlZCQU1USDJOdmRXTm9ZbUZ6ClpTMXZjR1Z5WVhSdmNpMWhaRzFwYzNOcGIyNGdRMEV3Z2dFaU1BMEdDU3FHU0liM0RRRUJBUVVBQTRJQkR3QXcKZ2dFS0FvSUJBUURTczdBcy9XSnFvWXVXdk5iK3FVVGpXaFpud3FjNmhRci8vV0E5SE9VUzZrWkxsQk9xR0oxUwpiVGw1OFkyNlRONi9TaFdlZjA1WXErQXV2Q0dsd1F3blUyZWJ0bnVyQzBwMFRNZnJIWVEvWXNBKytNdElldE9hCktrMEdaejdjaXp2ekowT1I0L3FkSGpZRTJpV3hFV2hyU1g5ZHNINWExZzFpTXB1elF3SE9rN0ZSZFY5aWxDbXAKSnZjVGJRMVBhOU1wSmI0OWYxYWlXVndPZE4zWkN6VWdJS1E0ZVpkOFlPZ0VSWXl5RStYY29NbHNlWFdiZGhHQQp5NVRSeVJ3OUZUZ3FIOWwrcWF6NTM4Q3U4a1lheWtzWUZ4UjYxdUl4Tko5N1FMU2gzV2tCTWFVRm9ac3YzM3VlClhpRHN3NkR3L3JwNFpoamlPYjZkdVRyd3dFTG56eE1GQWdNQkFBR2pRakJBTUE0R0ExVWREd0VCL3dRRUF3SUIKQmpBUEJnTlZIUk1CQWY4RUJUQURBUUgvTUIwR0ExVWREZ1FXQkJTb25TZE0rdlFabUVVZ0hLY0N1VUhoWEtGKwpaakFOQmdrcWhraUc5dzBCQVFzRkFBT0NBUUVBdE5uNldHVzg5N3Bqdzd6UC9ROXYxR0ltQUVnRlNYUmw4L1EzCjFaTjlkbytTMldIUlc5NWtnRHN4c0hJQ0JGcExGNTdKMUo1cEVINUlEbkxrbFN5U0hMVnd0ekd5TUNxbG4vaEcKcGVNNTZHaTgrazUwTFh0ckVrd0ZXR1JFTmZQL1JhMkZBU1ZnTTBqcHVvQnB6M3U0Z3BMVTl4c0Q1RGkxZTFvaApXV2xVVDh4VTBpeW5jVHJwSlFPR3c5eG1jMStSN2Qva0dUTTJiWDNtbmpvemI5TlpZeS8vSUkrb1ZLb0lNMWtMCmZlZytwaXRjdzBHditEQ2dMNWJVQitpY1d4QlJ4aDU2SklXK2FwMnFUcytyQUVPMXNhR2piQ3NTN0JzN295WHAKUzREVE9KWWNIYWs0elVTN2pENUI1QldpdGxvb3J0emRlaWRWUXNUenlKaHJOeDdrcXc9PQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
    service:
      name: couchbase-operator-admission
      namespace: default
      path: /couchbaseclusters/validate
  failurePolicy: Fail
  name: couchbase-operator-admission.default.svc
  rules:
  - apiGroups:
    - couchbase.com
    apiVersions:
    - v1
    - v2
    operations:
    - CREATE
    - UPDATE
    resources:
    - couchbaseclusters
    - couchbasebuckets
    - couchbaseephemeralbuckets
    - couchbasememcachedbuckets
    - couchbasereplications
    - couchbaseusers
    - couchbasegroups
    - couchbaserolebindings
    - couchbasebackups
    - couchbasebackuprestores
    - couchbaseautoscalers
    - couchbasecollections
    - couchbasecollectiongroups
    - couchbasescopes
    - couchbasescopegroups
    - couchbasemigrationreplications
  sideEffects: None
---
apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    config.couchbase.com/version: 2.5.0
  creationTimestamp: null
  name: couchbase-operator
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  annotations:
    config.couchbase.com/version: 2.5.0
  creationTimestamp: null
  name: couchbase-operator
rules:
- apiGroups:
  - batch
  resources:
  - jobs
  - cronjobs
  verbs:
  - list
  - watch
  - create
  - update
  - delete
- apiGroups:
  - couchbase.com
  resources:
  - couchbaseclusters
  - couchbaseclusters/finalizers
  verbs:
  - get
  - list
  - watch
  - update
- apiGroups:
  - couchbase.com
  resources:
  - couchbasereplications
  - couchbasemigrationreplications
  - couchbaseusers
  - couchbasegroups
  - couchbaserolebindings
  - couchbasebackups
  verbs:
  - list
  - watch
- apiGroups:
  - couchbase.com
  resources:
  - couchbasebuckets
  - couchbaseephemeralbuckets
  - couchbasememcachedbuckets
  - couchbasescopes
  - couchbasescopegroups
  - couchbasecollections
  - couchbasecollectiongroups
  verbs:
  - list
  - watch
  - create
- apiGroups:
  - couchbase.com
  resources:
  - couchbasebackuprestores
  verbs:
  - list
  - watch
  - delete
- apiGroups:
  - couchbase.com
  resources:
  - couchbaseautoscalers
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - delete
- apiGroups:
  - couchbase.com
  resources:
  - couchbaseautoscalers/status
  verbs:
  - update
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - delete
- apiGroups:
  - ""
  resources:
  - pods
  - pods/status
  - services
  - persistentvolumeclaims
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - delete
  - patch
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - list
  - create
  - update
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - get
  - create
  - update
  - list
  - watch
- apiGroups:
  - policy
  resources:
  - poddisruptionbudgets
  verbs:
  - get
  - create
  - delete
  - list
  - watch
- apiGroups:
  - coordination.k8s.io
  resources:
  - leases
  verbs:
  - get
  - create
  - update
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  annotations:
    config.couchbase.com/version: 2.5.0
  creationTimestamp: null
  name: couchbase-operator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: couchbase-operator
subjects:
- kind: ServiceAccount
  name: couchbase-operator
  namespace: default
---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    config.couchbase.com/version: 2.5.0
  creationTimestamp: null
  name: couchbase-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: couchbase-operator
  strategy: {}
  template:
    metadata:
      annotations:
        prometheus.io/path: /metrics
        prometheus.io/port: "8383"
        prometheus.io/scrape: "true"
      creationTimestamp: null
      labels:
        app: couchbase-operator
    spec:
      containers:
      - args:
        - --pod-create-timeout=10m0s
        - --pod-delete-delay=0s
        - --zap-log-level=info
        command:
        - couchbase-operator
        env:
        - name: WATCH_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        image: ghcr.io/cb-vanilla/operator:2.6.1-106
        imagePullPolicy: IfNotPresent
        name: couchbase-operator
        ports:
        - containerPort: 8080
          name: http
        - containerPort: 8383
          name: prometheus
        readinessProbe:
          httpGet:
            path: /readyz
            port: http
            scheme: HTTP
        resources: {}
      securityContext:
        runAsNonRoot: true
      serviceAccountName: couchbase-operator
      imagePullSecrets:
        - name: ghcr-login-secret
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    config.couchbase.com/version: 2.5.0
  creationTimestamp: null
  name: couchbase-operator
spec:
  ports:
  - name: http-pprof
    port: 8080
    protocol: TCP
    targetPort: 8080
  - name: http-prometheus
    port: 8383
    protocol: TCP
    targetPort: 8383
  selector:
    app: couchbase-operator

