apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    config.couchbase.com/version: 2.5.0
  creationTimestamp: null
  name: couchbase-operator-admission
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  annotations:
    config.couchbase.com/version: 2.5.0
  creationTimestamp: null
  name: couchbase-operator-admission
rules:
- apiGroups:
  - couchbase.com
  resources:
  - couchbaseclusters
  - couchbasebuckets
  - couchbaseephemeralbuckets
  - couchbasememcachedbuckets
  - couchbasereplications
  - couchbaseusers
  - couchbasegroups
  - couchbaserolebindings
  - couchbasebackups
  - couchbasebackuprestores
  - couchbaseautoscalers
  - couchbasecollections
  - couchbasecollectiongroups
  - couchbasescopes
  - couchbasescopegroups
  - couchbasemigrationreplications
  verbs:
  - get
  - list
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - get
- apiGroups:
  - storage.k8s.io
  resources:
  - storageclasses
  verbs:
  - get
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  annotations:
    config.couchbase.com/version: 2.5.0
  creationTimestamp: null
  name: couchbase-operator-admission
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: couchbase-operator-admission
subjects:
- kind: ServiceAccount
  name: couchbase-operator-admission
  namespace: default
---
apiVersion: v1
data:
  tls.crt: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURoekNDQW0rZ0F3SUJBZ0lRUFJOQ2tEdWFDUnVmbytRNVdqNkorakFOQmdrcWhraUc5dzBCQVFzRkFEQXEKTVNnd0pnWURWUVFERXg5amIzVmphR0poYzJVdGIzQmxjbUYwYjNJdFlXUnRhWE56YVc5dUlFTkJNQjRYRFRJegpNRFF4TURJek1qTTBORm9YRFRNek1EUXdOekl6TWpNME5Gb3dKekVsTUNNR0ExVUVBeE1jWTI5MVkyaGlZWE5sCkxXOXdaWEpoZEc5eUxXRmtiV2x6YzJsdmJqQ0NBU0l3RFFZSktvWklodmNOQVFFQkJRQURnZ0VQQURDQ0FRb0MKZ2dFQkFQSkpLODJ1UUkyeU1PWi9qWDl0SGJ1OS91UFFsdmt0dDdBdW1EV1lMVU04UVVQMjlpMjlvaTVUVFo2agoxNlJxRElhMldxNkZCaEFITmo3TGoyNFVrSmttWHZ2VC9FWFRGVEsxTUJMNUwyQkhmejBSN2tnbjZ4N2ZZZS9tCnA1RmdpY09pQ1pSeHYveUU0cXJlSjR2U2hUNm9ITDhySExHZ21iNXhZZVNtenFtRWFzWjFRMU5xS3lqNjRkUDYKbkFNSWN5VEhDR3JMbGdsOFpNUUxXY0VSVFdjWUVTcWEveURvSW9vUUZGblRnWXNlUDZLVldsZmRiS0V5Z29RSApJdXlQUGd5WUZ3UU5FWXFoQmYvcDVLNm5kYTdjWEJzY0FWQ3pLR3NsQ2Y4cGwvQTYvN05WUHBLajRRT3cyMEVVCjVFak1tbk5DejBoTS9JdFE2RmJIL3FqWUI4c0NBd0VBQWFPQnF6Q0JxREFPQmdOVkhROEJBZjhFQkFNQ0JhQXcKRXdZRFZSMGxCQXd3Q2dZSUt3WUJCUVVIQXdFd0RBWURWUjBUQVFIL0JBSXdBREFkQmdOVkhRNEVGZ1FVdWZnUwpiUjZFY0o5TStuOFJDeU9uS01PSEYvWXdId1lEVlIwakJCZ3dGb0FVU3R1R1BDYjh0TjQ4NDBsZ3Z2Nzc4V2g2Ckg0a3dNd1lEVlIwUkJDd3dLb0lvWTI5MVkyaGlZWE5sTFc5d1pYSmhkRzl5TFdGa2JXbHpjMmx2Ymk1a1pXWmgKZFd4MExuTjJZekFOQmdrcWhraUc5dzBCQVFzRkFBT0NBUUVBREZPNm03Z0tnN2ZIdHBsL0xjbkVuUWJCeTl1WQpTUTNwYm1Jdm1sajc1b3psWmJQdHRiTit5TitRSHEydW5BOGc4RnJSNFdJNDA0MW5lMHVMSGJUSEphQmxCS1lVClc0Rkp1eFEzWVVpSGFtM2JjUnhEd2JiaXk5Q0FaTTNxeC9rTzREa3hKaGJjYnM3N0JtN1oxRHZBWWxudEx6R3AKc2h5UW5lMDQyT254dDlXMThqZVR6NWF6dWlaYTFFbkUrS0E2NU9xRXZadUx0SlBNNVlBZkdlNHRGbTloS0RJWApaaFg1dzNoaDI5SWxYU0xlT2ZQMGpmNTlxZDl3QWlnOEVQRWVLN0UrdTM2cnhFT2JhUzNMbGlHL3lKbmdvTkFPCnd2NFl4MXk0UDRHSW13SVpFYVVTQUJYTXovUFViNkpFbUFoSzMvRndWQXQwNUdWbDBDbXZJbW5ScGc9PQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
  tls.key: LS0tLS1CRUdJTiBSU0EgUFJJVkFURSBLRVktLS0tLQpNSUlFcEFJQkFBS0NBUUVBOGtrcnphNUFqYkl3NW4rTmYyMGR1NzMrNDlDVytTMjNzQzZZTlpndFF6eEJRL2IyCkxiMmlMbE5ObnFQWHBHb01oclphcm9VR0VBYzJQc3VQYmhTUW1TWmUrOVA4UmRNVk1yVXdFdmt2WUVkL1BSSHUKU0Nmckh0OWg3K2Fua1dDSnc2SUpsSEcvL0lUaXF0NG5pOUtGUHFnY3Z5c2NzYUNadm5GaDVLYk9xWVJxeG5WRApVMm9yS1ByaDAvcWNBd2h6Sk1jSWFzdVdDWHhreEF0WndSRk5aeGdSS3ByL0lPZ2lpaEFVV2RPQml4NC9vcFZhClY5MXNvVEtDaEFjaTdJOCtESmdYQkEwUmlxRUYvK25rcnFkMXJ0eGNHeHdCVUxNb2F5VUoveW1YOERyL3MxVSsKa3FQaEE3RGJRUlRrU015YWMwTFBTRXo4aTFEb1ZzZitxTmdIeXdJREFRQUJBb0lCQVFDQStaQ1cyZ2JGSnpFKwowbkc1ZnBXUVpuQzBSMHJHOUo1TzdFN2NZTmpmYk1qMWJCYmFmSk5FQTlaUzk3Y0liK2VoSXB1ZFFYVGJ2V3NUCi9IcXF4OG05clI1dEFnak9CckxISG9xcjN2aG9VVWNiZEZzYkVCenFmMUY4U3BXekh1ZlhPMy9NQk0yRm1CdXQKaDdzWGhJYW50d2d1ZjcyemxPR2k3bXFGTklMWTIzcHZRZTV3NlJFblRBQVBuVDY2UE1wQ2FydUIyZ3AwcjljOQoxdEFxQU0yaVFQdzZ4Vzdpc1VIdkoycHk5SGYrQ3FLQUhrK0MrRkdYMWpnTkVVbEsxNmJ5OVFKNVg0NDJQYlF6CmdablFJdkx5VHl3dk45SFpxb3NraGlZUk1RS3F5d2IzeEMxaGhFSWJRczhReTlRM2luYlZkTGpPTnZ2dkdhblkKdlArTDdCYlpBb0dCQVBwaEZCVk5OYkhJSHd4QTN3Q0pDeitLRXVVYnFRcnFFK1BRRU9TdzRJN3NpdjFBZmhragpBYmkxL1U5WW1HLzNSUUd0UmxMcTd0QUIrZzRLNFBhdFoxMW84ZngydW9ndWNDTTlVTHJhM3p2VjljbjNYbmNpClBFUFNGSnVUVE5WUXhLT2Zxa001ejlpUjdjaEFwYnJERmdIckFVdXB4NG9KSzF4di9ZMTlCbXRuQW9HQkFQZTUKbEloODdDRG90b0RjUzJsbjdTKzhWV3Q5RHk4QTlCUjB3SW5oNXhhT1dDcmN0WGplS1lsZkVSUFAzSWJNUjhiLwpMQjRjeTVkQnVvN2hhWFdlUWFERDJTTGM5L1dwcmp5NDRsOCtDYXc2MFZpR3VzdDhaZSt4UXovMGEra1k3RHM1CjZaRDhPY01hb2FsNkptZnpmQUcxUTFNZmZONDhraWdCdHdmeDlpWDlBb0dBYzZILy8zS0FHTkllbks4ZERvYzgKUGFVTDR1bXFZVk1IeW8rZUxiQU9sWk5qQVdFV200OVNUVGNuZk15aTRocmxzTWVRa2R6VVhCWjlvSnlmbHUwdwpyckE0Q2V2ZmErTmVnTGZobjlwVGZMUHM1dENxdlFSL3BxYlFRNlY4dDR1c3RSQ1pOcUR0Zjh5dGIyMkQzTVFhClZ0cHM1Ny9LV3RLdlJ1cWx4QUY0eElNQ2dZQUZEY01xK2FsemptdlN1eXZLcmJVWUNUYVE1ODg4ZlQ5OWYxaEMKTjlxWUNqVmdRbnB0U2RMOUczUmt2QlBhcUNZNnVBLzFXVThKK2V4TlorblgzVytuVVBlSUQ0djdkZ2U0ODJpaQoyc2dsdkZseS9lU25yQlVFUzlCOGFJY2ZEVVFjZlRUM29UMm9iazJvQUhieUhmU0VzR2I4TmlNOUFXMVY1WnNQClRXOWhIUUtCZ1FEb1FleTdjbXVYcmJEaS8wMW5MOGRHcmJDUlIxcjhsUU9BUzNIUjNsdHFPRlZwbERGZGRtUXAKMGN0NXFaM201a01YZXhUeTVzM2tvZGxjbmcrTVNqMjRUNGtCTW00TTRaMnRaYklBNkZTdExFMWRsQWdSbUhZagpXWWZraTlITDBrLytQVWZSMyt0UHdiNjR1dVc4bWdsc1U5OEZHTjB0MEtBOUFVa2x0ZHRhMmc9PQotLS0tLUVORCBSU0EgUFJJVkFURSBLRVktLS0tLQo=
kind: Secret
metadata:
  annotations:
    config.couchbase.com/version: 2.5.0
  creationTimestamp: null
  name: couchbase-operator-admission
---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    config.couchbase.com/version: 2.5.0
  creationTimestamp: null
  name: couchbase-operator-admission
spec:
  replicas: 1
  selector:
    matchLabels:
      app: couchbase-operator-admission
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: couchbase-operator-admission
    spec:
      containers:
      - args:
        - -zap-log-level=info
        - -tls-cert-file=/var/run/secrets/couchbase.com/couchbase-operator-admission/tls.crt
        - -tls-private-key-file=/var/run/secrets/couchbase.com/couchbase-operator-admission/tls.key
        - -validate-secrets=true
        - -validate-storage-classes=true
        command:
        - couchbase-admission-controller
        image: ghcr.io/cb-vanilla/admission-controller:2.5.0-128
        imagePullPolicy: IfNotPresent
        name: couchbase-operator-admission
        ports:
        - containerPort: 8443
          name: https
        readinessProbe:
          httpGet:
            path: /readyz
            port: https
            scheme: HTTPS
        resources: {}
        volumeMounts:
        - mountPath: /var/run/secrets/couchbase.com/couchbase-operator-admission
          name: couchbase-operator-admission
          readOnly: true
      imagePullSecrets:
        - name: ghcr-login-secret
      securityContext:
        runAsNonRoot: true
      serviceAccountName: couchbase-operator-admission
      volumes:
      - name: couchbase-operator-admission
        secret:
          secretName: couchbase-operator-admission
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    config.couchbase.com/version: 2.5.0
  creationTimestamp: null
  name: couchbase-operator-admission
spec:
  ports:
  - port: 443
    protocol: TCP
    targetPort: 8443
  selector:
    app: couchbase-operator-admission
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  annotations:
    config.couchbase.com/version: 2.5.0
  creationTimestamp: null
  name: couchbase-operator-admission
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURJVENDQWdtZ0F3SUJBZ0lSQVB6NUYyWU4zdWwvaFFsTk96azE1bEF3RFFZSktvWklodmNOQVFFTEJRQXcKS2pFb01DWUdBMVVFQXhNZlkyOTFZMmhpWVhObExXOXdaWEpoZEc5eUxXRmtiV2x6YzJsdmJpQkRRVEFlRncweQpNekEwTVRBeU16SXpORFJhRncwek16QTBNRGN5TXpJek5EUmFNQ294S0RBbUJnTlZCQU1USDJOdmRXTm9ZbUZ6ClpTMXZjR1Z5WVhSdmNpMWhaRzFwYzNOcGIyNGdRMEV3Z2dFaU1BMEdDU3FHU0liM0RRRUJBUVVBQTRJQkR3QXcKZ2dFS0FvSUJBUUN0WVRzczFvRjErTHNBOFVxdUZ2VVBueGFPZ0ltQ0lGKzFZdzZqOHBpVW9iSm1Bci9wMWt1dwpybUJDWnVmUEZYQnpTTmFRSWFIajBCSmg1akVyYVFvY0JxYmgxYjRUWTJ0OGR0REJOY2hnRXI1blJkUGxiR09BCmRhY05ITXo2emtEcFZpY093NHpHejJ4eVRrTEZwVlpJS2MvT2pNNUFncTYzTW8zV28yUzVuakRaWUJYOHlHUUoKRFN2SmJ4enRqSTZBUTZzN1psaldMWXkrZGxCV0JMR0dkZGZ0M3k2LzZpMG5XYm5XZDFBWHZhV0pYRWs3a010NgpJd0NRWjRKZEFWZVJRTTl6MHMwUEVZeDFNcTVvWjhlTGI5RElHSFhrOEpBWFNqNXF6SmR0ZlJnd0pSaEdKbFBWCk5icWx0ZjRlSDVwcVM5ZXhObkUxUkkrSlhFNHJucTZEQWdNQkFBR2pRakJBTUE0R0ExVWREd0VCL3dRRUF3SUIKQmpBUEJnTlZIUk1CQWY4RUJUQURBUUgvTUIwR0ExVWREZ1FXQkJSSzI0WThKdnkwM2p6alNXQysvdnZ4YUhvZgppVEFOQmdrcWhraUc5dzBCQVFzRkFBT0NBUUVBcHRGZnkxekJNOTRYdmU4Z1JoYkJ1THJHSEpERUF1TUhKbkpHCitUY0UxakVYRDg5dTZmSXhwVEVvWFZKZW5USk84QkZPbm9vNzhZS3NzSlBIK3BsMkxsQVFtZW5Db1p4QkNGSXoKcmdFK0FSRVJxQlBGd3NTZ2ZCeVFZbi9WQjFodjM4L3NRa1NRbDVaOGducit2WXpFUnY4M1YvblRoOUp3bDVxTwovQTBwTENSbXlMQU1rY0tQMmRTRUhMY3dISk1oR0NzRGFRMWhsV2dSWlFmQXRra3BpTWJUelJreEZkZ01aNFB5CnEvY21iWFhzeVBVNm5ETXgzU1BobithQmNmN3h4dWU1cjNleE51aG5yTS9aNmF2ZW1xcER5TFpiNUVkVEYySHEKcnVadFR2Y2p6MHp3TnNCaGwzR28yV2NlOVJ3d28zRkxxRzltbjIxMlo5RmFRUmhXQkE9PQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
    service:
      name: couchbase-operator-admission
      namespace: default
      path: /couchbaseclusters/validate
  failurePolicy: Fail
  name: couchbase-operator-admission.default.svc
  rules:
  - apiGroups:
    - couchbase.com
    apiVersions:
    - v1
    - v2
    operations:
    - CREATE
    - UPDATE
    resources:
    - couchbaseclusters
    - couchbasebuckets
    - couchbaseephemeralbuckets
    - couchbasememcachedbuckets
    - couchbasereplications
    - couchbaseusers
    - couchbasegroups
    - couchbaserolebindings
    - couchbasebackups
    - couchbasebackuprestores
    - couchbaseautoscalers
    - couchbasecollections
    - couchbasecollectiongroups
    - couchbasescopes
    - couchbasescopegroups
    - couchbasemigrationreplications
  sideEffects: None
---
apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    config.couchbase.com/version: 2.5.0
  creationTimestamp: null
  name: couchbase-operator
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  annotations:
    config.couchbase.com/version: 2.5.0
  creationTimestamp: null
  name: couchbase-operator
rules:
- apiGroups:
  - batch
  resources:
  - jobs
  - cronjobs
  verbs:
  - list
  - watch
  - create
  - update
  - delete
- apiGroups:
  - couchbase.com
  resources:
  - couchbaseclusters
  - couchbaseclusters/finalizers
  verbs:
  - get
  - list
  - watch
  - update
- apiGroups:
  - couchbase.com
  resources:
  - couchbasereplications
  - couchbasemigrationreplications
  - couchbaseusers
  - couchbasegroups
  - couchbaserolebindings
  - couchbasebackups
  verbs:
  - list
  - watch
- apiGroups:
  - couchbase.com
  resources:
  - couchbasebuckets
  - couchbaseephemeralbuckets
  - couchbasememcachedbuckets
  - couchbasescopes
  - couchbasescopegroups
  - couchbasecollections
  - couchbasecollectiongroups
  verbs:
  - list
  - watch
  - create
- apiGroups:
  - couchbase.com
  resources:
  - couchbasebackuprestores
  verbs:
  - list
  - watch
  - delete
- apiGroups:
  - couchbase.com
  resources:
  - couchbaseautoscalers
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - delete
- apiGroups:
  - couchbase.com
  resources:
  - couchbaseautoscalers/status
  verbs:
  - update
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - delete
- apiGroups:
  - ""
  resources:
  - pods
  - pods/status
  - services
  - persistentvolumeclaims
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - delete
  - patch
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - list
  - create
  - update
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - get
  - create
  - update
  - list
  - watch
- apiGroups:
  - policy
  resources:
  - poddisruptionbudgets
  verbs:
  - get
  - create
  - delete
  - list
  - watch
- apiGroups:
  - coordination.k8s.io
  resources:
  - leases
  verbs:
  - get
  - create
  - update
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  annotations:
    config.couchbase.com/version: 2.5.0
  creationTimestamp: null
  name: couchbase-operator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: couchbase-operator
subjects:
- kind: ServiceAccount
  name: couchbase-operator
  namespace: default
---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    config.couchbase.com/version: 2.5.0
  creationTimestamp: null
  name: couchbase-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: couchbase-operator
  strategy: {}
  template:
    metadata:
      annotations:
        prometheus.io/path: /metrics
        prometheus.io/port: "8383"
        prometheus.io/scrape: "true"
      creationTimestamp: null
      labels:
        app: couchbase-operator
    spec:
      containers:
      - args:
        - --pod-create-timeout=10m0s
        - --pod-delete-delay=0s
        - --zap-log-level=info
        command:
        - couchbase-operator
        env:
        - name: WATCH_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        image: ghcr.io/cb-vanilla/operator:2.5.0-128
        imagePullPolicy: IfNotPresent
        name: couchbase-operator
        ports:
        - containerPort: 8080
          name: http
        - containerPort: 8383
          name: prometheus
        readinessProbe:
          httpGet:
            path: /readyz
            port: http
            scheme: HTTP
        resources: {}
      imagePullSecrets:
        - name: ghcr-login-secret
      securityContext:
        runAsNonRoot: true
      serviceAccountName: couchbase-operator
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    config.couchbase.com/version: 2.5.0
  creationTimestamp: null
  name: couchbase-operator
spec:
  ports:
  - name: http-pprof
    port: 8080
    protocol: TCP
    targetPort: 8080
  - name: http-prometheus
    port: 8383
    protocol: TCP
    targetPort: 8383
  selector:
    app: couchbase-operator

