apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: couchbasecluster
rules:
- apiGroups:
  - couchbase.com
  resources:
  - couchbaseclusters
  - couchbasebuckets
  - couchbaseephemeralbuckets
  - couchbasememcachedbuckets
  - couchbasereplications
  - couchbaseusers
  - couchbasegroups
  - couchbaseroles
  - couchbaseuserrolebindings
  - couchbasebackups
  - couchbasebackuprestores
  verbs:
  - "*"
